pipeline {
    agent any
    stages {
        stage("Cloning Repository") {
            steps {
                git branch: 'master', url: 'https://github.com/henrik-olvr/provisioning-vault.git'
            }
        }
        stage("Provisioning") {
            steps {
                sh 'ansible-playbook ansible-and-jenkins/ansible/playbook.yml'
            }
        }
    }
}
